/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lockdown_traveller;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.Socket;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ajendrasaxena
 */
public class Showcancelled extends javax.swing.JFrame {
String p1a="-1",p2a="-1",p3a="-1",p4a="-1",p5a="-1";
String p1n="-1",p2n="-1",p3n="-1",p4n="-1",p5n="-1",passn="",passw="";
    String p1g="-1",p2g="-1",p3g="-1",p4g="-1",p5g="-1";
    String p1p="-1",p2p="-1",p3p="-1",p4p="-1",p5p="-1";
    String p1b="-1",p2b="-1",p3b="-1",p4b="-1",p5b="-1";
    /**
     * Creates new form Showcancelled
     */
    static String pnr,username;
    public Showcancelled() {
        initComponents();
    }
public void func() throws IOException{
    Socket s= new Socket("localhost",9160);
    DataOutputStream dout=new DataOutputStream(s.getOutputStream());
    DataInputStream din=new DataInputStream(s.getInputStream());
    dout.writeUTF(pnr);
    username=din.readUTF();
    tname.setText("Train Name : "+din.readUTF());
    tnum.setText("Train number : "+din.readUTF());
    doj.setText("Date of journey : "+din.readUTF());
    p1n=din.readUTF();
    p1a=din.readUTF();
    p1g=din.readUTF();
    p1b=din.readUTF();
    p2n=din.readUTF();
    p2a=din.readUTF();
    p2g=din.readUTF();
    p2b=din.readUTF();
    p3n=din.readUTF();
    p3a=din.readUTF();
    p3g=din.readUTF();
    p3b=din.readUTF();
    p4n=din.readUTF();
    p4a=din.readUTF();
    p4g=din.readUTF();
    p4b=din.readUTF();
    p5n=din.readUTF();
    p5a=din.readUTF();
    p5g=din.readUTF();
    p5b=din.readUTF();
    source.setText("Source : "+din.readUTF());
    dest.setText("Destination : "+din.readUTF());
    fare.setText("Fare : "+din.readUTF());
    dist.setText("Distance : "+din.readUTF());
    clas.setText("Class : "+din.readUTF());
    DefaultTableModel model = (DefaultTableModel) table.getModel();
        
    if(!p1n.equalsIgnoreCase("-1")){
        Object row[]={p1n,p1a,p1b,p1g};
        
        model.addRow(row);
    }
    if(!p2n.equalsIgnoreCase("-1")){
        Object row[]={p2n,p2a,p2b,p2g};
        
        model.addRow(row);
    }
    if(!p3n.equalsIgnoreCase("-1")){
        Object row[]={p3n,p3a,p3b,p3g};
        
        model.addRow(row);
    }
    if(!p4n.equalsIgnoreCase("-1")){
        Object row[]={p4n,p4a,p4b,p4g};
        
        model.addRow(row);
    }
    if(!p5n.equalsIgnoreCase("-1")){
        Object row[]={p5n,p5a,p5b,p5g};
        
        model.addRow(row);
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tnum = new javax.swing.JLabel();
        fare = new javax.swing.JLabel();
        tname = new javax.swing.JLabel();
        dist = new javax.swing.JLabel();
        doj = new javax.swing.JLabel();
        source = new javax.swing.JLabel();
        clas = new javax.swing.JLabel();
        dest = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tnum.setText("jLabel1");

        fare.setText("jLabel2");

        tname.setText("a\\");

            dist.setText("jLabel4");

            doj.setText("jLabel5");

            source.setText("jLabel6");

            clas.setText("jLabel7");

            dest.setText("jLabel8");

            table.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                    "Name", "Age", "Seat", "Gender"
                }
            ) {
                Class[] types = new Class [] {
                    java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
                };
                boolean[] canEdit = new boolean [] {
                    true, true, false, true
                };

                public Class getColumnClass(int columnIndex) {
                    return types [columnIndex];
                }

                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit [columnIndex];
                }
            });
            jScrollPane1.setViewportView(table);

            jButton1.setText("OK");
            jButton1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(73, 73, 73)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tnum, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                                        .addComponent(tname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(doj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(clas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(59, 59, 59)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(fare, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                        .addComponent(dist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(source, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(dest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(180, 180, 180)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addContainerGap())
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(40, 40, 40)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tnum)
                        .addComponent(fare))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(dist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(doj)
                        .addComponent(source))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(clas)
                        .addComponent(dest))
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jButton1)
                    .addContainerGap(29, Short.MAX_VALUE))
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Showcancelled.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Showcancelled.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Showcancelled.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Showcancelled.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Showcancelled().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel clas;
    private javax.swing.JLabel dest;
    private javax.swing.JLabel dist;
    private javax.swing.JLabel doj;
    private javax.swing.JLabel fare;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel source;
    private javax.swing.JTable table;
    private javax.swing.JLabel tname;
    private javax.swing.JLabel tnum;
    // End of variables declaration//GEN-END:variables
}
